spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.aliyun.odps.jdbc.OdpsDriver
    url:
    username:
    password:

    #自定义多数据源属性
    #预发mysql
    mysql:
      url:
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
    #线上odps
    odps:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.aliyun.odps.jdbc.OdpsDriver
      url:
      username:
      password:
      defaultAutoCommit: false
    druid:
      default-auto-commit: false
